### ISSUE TITLE
MissingObjectException when trying to GET a non-existing resource

### ISSUE THREAD

**Issue by holycrab13** [dbpedia/gstore#34]
Stacktrace: 

```
08:42:41.254 WARN  ROOT - org.dbpedia.databus.swagger.api.DefaultApi: Error processing request
org.eclipse.jgit.errors.MissingObjectException: Missing unknown 0000000000000000000000000000000000000000
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:135)
	at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:143)
	at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:113)
	at org.eclipse.jgit.lib.Repository.open(Repository.java:331)
	at org.dbpedia.databus.LocalGitClient.$anonfun$readFile$2(GitClient.scala:77)
	at scala.util.Try$.apply(Try.scala:209)
	at org.dbpedia.databus.LocalGitClient.$anonfun$readFile$1(GitClient.scala:62)
	at org.dbpedia.databus.LocalGitClient.wrapWithSync(GitClient.scala:131)
	at org.dbpedia.databus.LocalGitClient.readFile(GitClient.scala:62)
	at org.dbpedia.databus.ApiImpl.readFile(ApiImpl.scala:119)
	at org.dbpedia.databus.ApiImpl.getFile(ApiImpl.scala:53)
	at org.dbpedia.databus.swagger.api.DefaultApi.$anonfun$new$6(DefaultApi.scala:121)
	at org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:280)
	at org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:274)
	at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:183)
	at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:169)
	at org.dbpedia.databus.swagger.api.DefaultApi.withRouteMultiParams(DefaultApi.scala:32)
	at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:273)
	at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:272)
	at org.dbpedia.databus.swagger.api.DefaultApi.org$scalatra$json$JsonSupport$$super$invoke(DefaultApi.scala:32)
	at org.scalatra.json.JsonSupport.$anonfun$invoke$1(JsonSupport.scala:90)
	at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:183)
	at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:169)
	at org.dbpedia.databus.swagger.api.DefaultApi.withRouteMultiParams(DefaultApi.scala:32)
	at org.scalatra.json.JsonSupport.invoke(JsonSupport.scala:84)
	at org.scalatra.json.JsonSupport.invoke$(JsonSupport.scala:83)
	at org.dbpedia.databus.swagger.api.DefaultApi.invoke(DefaultApi.scala:32)
	at org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:248)
	at scala.Option.flatMap(Option.scala:171)
	at org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:246)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:486)
	at org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:245)
	at org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:243)
	at org.dbpedia.databus.swagger.api.DefaultApi.runRoutes(DefaultApi.scala:32)
	at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:199)
	at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
	at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
	at org.dbpedia.databus.swagger.api.DefaultApi.executeRoutes(DefaultApi.scala:32)
	at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
	at org.dbpedia.databus.swagger.api.DefaultApi.withResponse(DefaultApi.scala:32)
	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at org.dbpedia.databus.swagger.api.DefaultApi.withRequest(DefaultApi.scala:32)
	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
	at org.dbpedia.databus.swagger.api.DefaultApi.withRequestResponse(DefaultApi.scala:32)
	at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
	at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
	at org.dbpedia.databus.swagger.api.DefaultApi.org$scalatra$servlet$ServletBase$$super$handle(DefaultApi.scala:32)
	at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
	at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
	at org.dbpedia.databus.swagger.api.DefaultApi.org$scalatra$servlet$FileUploadSupport$$super$handle(DefaultApi.scala:32)
	at org.scalatra.servlet.FileUploadSupport.handle(FileUploadSupport.scala:95)
	at org.scalatra.servlet.FileUploadSupport.handle$(FileUploadSupport.scala:80)
	at org.dbpedia.databus.swagger.api.DefaultApi.org$scalatra$CorsSupport$$super$handle(DefaultApi.scala:32)
	at org.scalatra.CorsSupport.$anonfun$handle$1(CORSSupport.scala:221)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
	at org.dbpedia.databus.swagger.api.DefaultApi.withResponse(DefaultApi.scala:32)
	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at org.dbpedia.databus.swagger.api.DefaultApi.withRequest(DefaultApi.scala:32)
	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
	at org.dbpedia.databus.swagger.api.DefaultApi.withRequestResponse(DefaultApi.scala:32)
	at org.scalatra.CorsSupport.handle(CORSSupport.scala:209)
	at org.scalatra.CorsSupport.handle$(CORSSupport.scala:206)
	at org.dbpedia.databus.swagger.api.DefaultApi.handle(DefaultApi.scala:32)
	at org.scalatra.ScalatraServlet.service(ScalatraServlet.scala:65)
	at org.scalatra.ScalatraServlet.service$(ScalatraServlet.scala:64)
	at org.dbpedia.databus.swagger.api.DefaultApi.service(DefaultApi.scala:32)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:856)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:319)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:133)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
	at java.lang.Thread.run(Thread.java:748)
```

Happens when trying to GET a resource that does not exist.

Expected: 404 Not Found

**Comment by manonthegithub** [comment]
Fixed

**Comment by manonthegithub** [comment]
in dev branch
